### ISSUE TITLE
Features.

### ISSUE THREAD

**Issue by holden** [razrfly/recordtemple#108]
* [x] HIDE the price model for people NOT logged in THIS IS EXTREMELY IMPORTANT
* [x] Remove `default_scope`
* [x] Prices should show up when logged in to YOUR records.
* [x] Install dropzone for both audio and images.
* [x] Double check that All formats work.
* [x] Ability to add records w/o price_guide prices.
* [ ] Re-import Osbourne DB. DISCUSS
* [x] General search feature (aka not ransack)

**Comment by tchorzewski1991** [comment]
Search completed 👍 

![search](https://cloud.githubusercontent.com/assets/13417596/18910261/7eb76750-8577-11e6-8872-949cab067714.jpg)

I have a question, what with that re-import?

**Comment by holden** [comment]
It means re-scraping this http://www.jerryosborne.com/cyberguides.htm, i did it 5 years ago, it's where prices came from. Word docs -> HTML -> SQL
