### ISSUE TITLE
Records index view changes

### ISSUE THREAD

**Issue by holden** [razrfly/recordtemple#115]
* [x] Move Labels form after Artists, it's 2nd more important
* [ ] Selectize add-on for an `X` would be better for removing options (better than backspace)
* [x] Condition can be a set of tick boxes, instead of dropdown? (names are also weird) but hidden in a show/hide type thing.
* [x] Non-functioning selectize arrows (dropdowns) are weird on ajax forms
* [x] Add images to results (with lightbox feature too later? after #114)
* [x] Search by price range (high and low) but ONLY shown if logged in.

**Comment by tchorzewski1991** [comment]
Everything what is checked on that list works as intended, except that 'x' plugin. I don't know if is it possible to make it work. That 'x' plugin is in most cases used for multiple options fields, and form text inputs ... we have select fields here.

**Comment by holden** [comment]
Everything looks good except i don't like the price slider, it also won't make sense as the range can go from 0 to 1000.  It should be just two simple boxes with either of them able to leave blank.

**Comment by tchorzewski1991** [comment]
ok, I will replace it

**Comment by holden** [comment]
We will need one more somewhat strange search feature as well...

There's record_type and record_format... we need to be able to search by both as groups and subgroups.

![amazon_de__buying_choices__withings_activite_sapphire_-_smartwatch_mit_aktivitats-_und_schlaftracker_-_schweizer_fabrikat_-silber_braun](https://cloud.githubusercontent.com/assets/48241/19146007/dd812ec0-8bb1-11e6-8c2f-0ef2a4ce62b9.png)

**Comment by holden** [comment]
But I would like a proposed solution first.  There's more than one way to do it.  In most cases search by 45s / or LP.

**Comment by tchorzewski1991** [comment]
Looks like this for now:

![search-index](https://cloud.githubusercontent.com/assets/13417596/19152068/765ae7c6-8bd0-11e6-9c82-cc467f612a74.jpg)
