### ISSUE TITLE
Missing things.

### ISSUE THREAD

**Issue by holden** [razrfly/recordtemple#117]
# Record show view changes

* [x] Price Guide info needs its own box.
* [x] Missing price information, both for Price Guide (only shown in logged-in)
* [x] And missing from Record too (price should be a range like year) only show if logged-in AND it's their record.
* [x] Songs should someone display the list of all of them. (ex: http://recordtemple.com/records/426, this record has two songs, it would be better if it would show all of them)

# Index changes

* [x] How to remove options is very unclear, we need some sort of 'X's removing the selectize options
* [x] The down arrows on ajax forms is extremely confusing.

**Comment by tchorzewski1991** [comment]
Would you like to have that player on records show page?  if yes it looks like this:
![songs-shit](https://cloud.githubusercontent.com/assets/13417596/19186395/59c617f0-8c86-11e6-92b5-2da8ef341494.jpg)

Or should I provide something like on records/edit ?  table + list ?

![songs-cool](https://cloud.githubusercontent.com/assets/13417596/19186407/6e7e2c28-8c86-11e6-8cca-73187aa095d3.jpg)

**Comment by holden** [comment]
Neither actually.  I'd prefer it be inline.

![soundmanager_2__bar_ui_player__prototype_](https://cloud.githubusercontent.com/assets/48241/19190376/7b3b7d1e-8c9d-11e6-8620-01cc1df64a10.png)

http://www.schillmania.com/projects/soundmanager2/demo/bar-ui/
