### ISSUE TITLE
Big changes.

### ISSUE THREAD

**Issue by holden** [razrfly/recordtemple#122]
* [x] Change show routes (http://recordtemple.com/records/11442) -> http://recordtemple.com/records/:artist-name-:label-11442
* [x] Partialized views for Labels and Artists (eg. https://www.artsy.net/artist/andy-warhol) Slider up top (10-20 records) and records ransack search con'd (scoped to artist or label) below.
* [x] Fix titles everywhere, no record temple, should have the most important info for each page (add to layout).
* [x] Selectize multi-tags is cool, add for labels too.
* [x] Comment should combine with price details / footnotes too on ransack should be called (Details with the hint "tracks, song titles, etc.")

**Comment by smadeja** [comment]
> Change show routes (http://recordtemple.com/records/11442) -> http://recordtemple.com/records/:artist-name-:label/11442

Why would you want something this terrible?

**Comment by holden** [comment]
It's a typo!

**Comment by smadeja** [comment]
It's just slugs on artsy.

**Comment by holden** [comment]
why would they always put a number then? there's no andy-warhol-pine-barrens-tree-frog-15!

**Comment by smadeja** [comment]
https://www.artsy.net/artwork/joseph-beuys-capri-batterie

**Comment by holden** [comment]
hmmmm.... you got me.
