### ISSUE TITLE
More changes.

### ISSUE THREAD

**Issue by holden** [razrfly/recordtemple#125]
![records](https://cloud.githubusercontent.com/assets/48241/19350073/9568d566-9156-11e6-9886-af2e1eb17965.png)

* [x] Should be links to artists / labels / genre
* [x] Need to add Genre's just like labels & artists (you can ignore index for now, just show is fine)
* [x] Can records table all share the same partial since they are all the same? (maybe they do now?)
* [x] Ransack sortable for artist / label / genre / record type
* [x] Basic breadcrumps #91

**Comment by tchorzewski1991** [comment]
Records table is shared already. Tables on Artist, Label and Records are the same partial.
