### ISSUE TITLE
Small changes.

### ISSUE THREAD

**Issue by holden** [razrfly/recordtemple#143]
<img width="859" alt="new_record" src="https://user-images.githubusercontent.com/48241/32620505-3aa03e1e-c57e-11e7-87e0-d71fcbe0b394.png">

* Label search is broken
* Detail field is missing? (title and number of record, basically are there any fields missing or where these all on Price?)
* Ability to Add new record labels & artists.
* Possibly add a year? (perhaps not)

**Comment by tchorzewski1991** [comment]
- Label search fixed.
- Detail attribute is defined on Price model, so I can't inject it into form for new priceless records.
- Ability to add new record labels and artists working correctly.

**Comment by holden** [comment]
Ok, looks better.  Last thing.

Can you change the order.

* Artist
* Label
* Genre
* Record type
* Price
* Identifier
* Comment

And combine some of these smaller fields together to make the form a bit smaller?

**Comment by tchorzewski1991** [comment]
Looks like this:

![repositioned](https://user-images.githubusercontent.com/13417596/34440515-f6e65e74-ecb5-11e7-93a2-a23751df79b1.jpg)
