### ISSUE TITLE
potentially replace jPlayer

### ISSUE THREAD

**Issue by holden** [razrfly/recordtemple#38]
http://www.schillmania.com/projects/soundmanager2/demo/bar-ui/

![soundmanager_2__bar_ui_player__prototype_](https://cloud.githubusercontent.com/assets/48241/6147241/994b1730-b1f5-11e4-88fe-310040024f41.png)

https://github.com/sudara/soundmanager2-rails

Or maybe rails assets?

**Comment by smadeja** [comment]
It's not available on Rails Assets. Also, Rails Assets are no better than Bower when it comes to managing dependencies. :-(

The gem looks nice, though.

**Comment by holden** [comment]
Let's use the gem then.  This plugin looks nice! and we're never going to need video support and the current player doesn't work correctly in production, probably some asset pipeline fun that would be better to avoid if the gem will do it for us.
