### ISSUE TITLE
Adding new records.

### ISSUE THREAD

**Issue by holden** [razrfly/recordtemple#99]
This isn't quite so straightforward.

* Creating new `records` are dependent on related `price_guide` prices.
* You need to search the price guide, find the record.
* Create new record based on price guide

**Comment by tchorzewski1991** [comment]
Index for prices - do we need something more to search?

![recordtemple](https://cloud.githubusercontent.com/assets/13417596/18386544/0718556c-7698-11e6-82c0-44f27bda8fad.jpg)

**Comment by tchorzewski1991** [comment]
And this is show view:

![recordtemple-show](https://cloud.githubusercontent.com/assets/13417596/18390672/7d6e1018-76ab-11e6-9e81-421308fcaa46.jpg)

**Comment by holden** [comment]
Probably `detail_and_footnotes` combined which is quite easy with the gem.

**Comment by holden** [comment]
* For the show view maybe just combine Year begin and year end as 1925-1930 if both, or if only one just put year... a very simple helper.  
* Artist and Label should be a header... they're the most important, shouldn't be in the bottom, 
* Records in price need to be scoped to the user... Prices are universal, but records are personal.
* Need an `Add Record` button, to create a new record from the price.
